apiVersion: v1
kind: Service
metadata:
  name: pg-service
  labels:
    app.service.name: postgres
spec:
  ports:
    - name: tcp-port
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app.service.name: postgres
